packages:
  - apps/*
  - packages/*

hoistPattern:
  - '*'
  - '!@strapi/*'

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@swc/core'
  - better-sqlite3
  - core-js-pure
  - esbuild
  - sharp

publicHoistPattern:
  - '*'
  - '!@strapi/*'
